using System.Collections.Generic;
using Graphing.Controls.Rendering.Geometry;

namespace Graphing.Controls.Presentation
{
    /// <summary>
    /// Phase P3 output: layout-resolved presentation model.
    /// Describes where the plot area and axes are positioned in abstract space,
    /// completely device- and renderer-neutral.
    /// </summary>
    public sealed class GraphLayoutModel
    {
        public GraphLayoutModel(
            PlotAreaLayout plotArea,
            IReadOnlyList<AxisLayoutEntry> axes,
            IReadOnlyList<SeriesPresentationGeometry> series)
        {
            PlotArea = plotArea;
            Axes = axes;
            Series = series;
            GridLines = new GridLinesGeometry(new List<GridLineGeometry>(), new List<GridLineGeometry>());
            Legend = null;
            AxisTitleBands = new List<AxisTitleBandGeometry>();
            EdgePaddingBands = new List<EdgePaddingBandGeometry>();
            AxisHitRegions = new List<AxisHitRegionGeometry>();
            AxisInteractionAffordanceRegions = new List<AxisInteractionAffordanceGeometry>();
        }

        public GraphLayoutModel(
            PlotAreaLayout plotArea,
            IReadOnlyList<AxisLayoutEntry> axes,
            IReadOnlyList<SeriesPresentationGeometry> series,
            TitlePresentationGeometry title = null,
            SubtitlePresentationGeometry subtitle = null,
            GridLinesGeometry gridLines = null,
            LegendPresentationGeometry legend = null,
            IReadOnlyList<AxisTitleBandGeometry> axisTitleBands = null,
            IReadOnlyList<EdgePaddingBandGeometry> edgePaddingBands = null,
            IReadOnlyList<AxisHitRegionGeometry> axisHitRegions = null,
            IReadOnlyList<AxisInteractionAffordanceGeometry> axisInteractionAffordanceRegions = null)
        {
            PlotArea = plotArea;
            Axes = axes;
            Series = series;
            Title = title;
            Subtitle = subtitle;
            GridLines = gridLines ?? new GridLinesGeometry(new List<GridLineGeometry>(), new List<GridLineGeometry>());
            Legend = legend;
            AxisTitleBands = axisTitleBands ?? new List<AxisTitleBandGeometry>();
            EdgePaddingBands = edgePaddingBands ?? new List<EdgePaddingBandGeometry>();
            AxisHitRegions = axisHitRegions ?? new List<AxisHitRegionGeometry>();
            AxisInteractionAffordanceRegions = axisInteractionAffordanceRegions ?? new List<AxisInteractionAffordanceGeometry>();
        }

        /// <summary>
        /// Abstract bounds of the plot area, excluding space allocated to axes.
        /// Expressed in a normalized unit square [0,1] x [0,1].
        /// </summary>
        public PlotAreaLayout PlotArea { get; }

        /// <summary>
        /// Axes included in the layout, each associated with a semantic side and ordered position.
        /// Left-side axes are capped at 6; any additional left-side axes are excluded.
        /// </summary>
        public IReadOnlyList<AxisLayoutEntry> Axes { get; }

        /// <summary>
        /// Series geometry forwarded from Phase P1.
        /// </summary>
        public IReadOnlyList<SeriesPresentationGeometry> Series { get; }

        /// <summary>
        /// Title presentation geometry (if title is present).
        /// </summary>
        public TitlePresentationGeometry Title { get; }

        /// <summary>
        /// Subtitle presentation geometry (if subtitle is present).
        /// </summary>
        public SubtitlePresentationGeometry Subtitle { get; }

        /// <summary>
        /// Grid lines aligned with axis ticks and clipped to plot area bounds.
        /// </summary>
        public GridLinesGeometry GridLines { get; }

        /// <summary>
        /// Legend container and entries rendered as part of layout output.
        /// </summary>
        public LegendPresentationGeometry Legend { get; }

        /// <summary>
        /// Immutable axis-title bands and items generated by the layout model.
        /// </summary>
        public IReadOnlyList<AxisTitleBandGeometry> AxisTitleBands { get; }

        /// <summary>
        /// Fixed edge-padding bands that separate all content from control boundaries.
        /// </summary>
        public IReadOnlyList<EdgePaddingBandGeometry> EdgePaddingBands { get; }

        /// <summary>
        /// Per-axis spine hit regions in abstract normalized geometry space.
        /// </summary>
        public IReadOnlyList<AxisHitRegionGeometry> AxisHitRegions { get; }

        /// <summary>
        /// Per-axis interaction affordance regions in abstract normalized geometry space.
        /// These regions represent user-intent capture geometry and are distinct from visual hit regions.
        /// </summary>
        public IReadOnlyList<AxisInteractionAffordanceGeometry> AxisInteractionAffordanceRegions { get; }

        /// <summary>
        /// Resolves the first matching axis hit region in stable layout order.
        /// Border points are inclusive and deterministic: first region in AxisHitRegions order wins.
        /// </summary>
        public AxisHitRegionGeometry ResolveHitAxisRegion(GeometryPoint3D point)
        {
            for (var i = 0; i < AxisInteractionAffordanceRegions.Count; i++)
            {
                var affordance = AxisInteractionAffordanceRegions[i];
                if (affordance == null)
                {
                    continue;
                }

                if (ContainsInclusive(affordance, point))
                {
                    return new AxisHitRegionGeometry(
                        affordance.AxisId,
                        affordance.Side,
                        affordance.Orientation,
                        0d,
                        0d,
                        affordance.BottomLeft,
                        affordance.TopRight);
                }
            }

            for (var i = 0; i < AxisHitRegions.Count; i++)
            {
                var region = AxisHitRegions[i];
                if (region == null)
                {
                    continue;
                }

                if (ContainsInclusive(region, point))
                {
                    return region;
                }
            }

            return null;
        }

        /// <summary>
        /// Resolves the identifier of the first axis hit region that contains the point.
        /// Returns null when no axis hit region contains the point.
        /// </summary>
        public string ResolveHitAxisId(GeometryPoint3D point)
        {
            var region = ResolveHitAxisRegion(point);
            return region != null ? region.AxisId : null;
        }

        private static bool ContainsInclusive(AxisHitRegionGeometry region, GeometryPoint3D point)
        {
            return point.X >= region.BottomLeft.X
                && point.X <= region.TopRight.X
                && point.Y >= region.BottomLeft.Y
                && point.Y <= region.TopRight.Y;
        }

        private static bool ContainsInclusive(AxisInteractionAffordanceGeometry region, GeometryPoint3D point)
        {
            return point.X >= region.BottomLeft.X
                && point.X <= region.TopRight.X
                && point.Y >= region.BottomLeft.Y
                && point.Y <= region.TopRight.Y;
        }
    }
}
