<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\UnitRegistry\src\UnitRegistry.Core\UnitRegistry.Core.csproj" />
    <ProjectReference Include="..\..\..\UnitRegistry\src\UnitRegistry.Formatting\UnitRegistry.Formatting.csproj" />
    <ProjectReference Include="..\Graphing.Controls\Graphing.Controls.csproj" />
    <ProjectReference Include="..\Graphing.Editors\Graphing.Editors.csproj" />
    <ProjectReference Include="..\Graphing.TestScenarios\Graphing.TestScenarios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AxisUnitAndNumericFormatDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>