<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphing.Controls\Graphing.Controls.csproj" />
    <ProjectReference Include="..\Graphing.Core\Graphing.Core.csproj" />
    <ProjectReference Include="..\..\..\UnitRegistry\src\UnitRegistry.Core\UnitRegistry.Core.csproj" />
    <ProjectReference Include="..\..\..\UnitRegistry\src\UnitRegistry.Formatting\UnitRegistry.Formatting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="EngineeringGraphControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>