<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net6.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphing.Controls\Graphing.Controls.csproj" />
  </ItemGroup>

</Project>
