<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphing.Controls\Graphing.Controls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\AxesEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\LegendEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\SeriesEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\TitlesEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="EngineeringGraphOptionsEditorForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
